import fg from "fast-glob";
import path from "path";
import { loadConfig, resolveProjectPaths } from "../config";
import { MemoryDatabase, deleteSourceEntries, loadIndexingStateMap, upsertIndexedFile } from "../db";
import { MemoryEntryRecord, MemoryHubConfig, MemorySourceType, ParsedChunk } from "../types";
import { readTextFile } from "../utils/fs";
import { sha256, shortId } from "../utils/hash";
import { parseMarkdownFile } from "./markdown";

// Phase 1 basenames — excluded from Phase 2 doc indexing to avoid duplication.
const PHASE1_BASENAMES = new Set([
  "INDEX.md",
  "PROJECT_CONTEXT.md",
  "ARCHITECTURE.md",
  "DECISIONS.md",
  "BUGS.md",
  "WORKLOG.md",
]);

// Files generated by Memory Hub itself — skip to avoid self-referential loops.
const GENERATED_BASENAMES = new Set([
  "memory-synthesis.md",
  "doc-synthesis.md",
]);

export type DocArtifactType =
  | "spec"
  | "plan"
  | "tasks"
  | "research"
  | "data-model"
  | "security"
  | "constitution"
  | "readme"
  | "architecture"
  | "doc";

export interface IndexDocOptions {
  refreshOnly?: boolean;
  removeDeleted?: boolean;
}

export interface IndexDocResult {
  scannedFiles: number;
  indexedFiles: number;
  skippedFiles: number;
  deletedFiles: number;
  indexedEntries: number;
}

export function inferArtifactType(relPath: string): DocArtifactType {
  const basename = path.basename(relPath).toLowerCase();
  if (basename === "spec.md") return "spec";
  if (basename === "plan.md") return "plan";
  if (basename === "tasks.md") return "tasks";
  if (basename === "research.md") return "research";
  if (basename === "data-model.md" || basename === "datamodel.md") return "data-model";
  if (basename.includes("security")) return "security";
  if (
    basename === "constitution.md" ||
    basename === "architecture_constitution.md" ||
    basename === "security_constitution.md"
  )
    return "constitution";
  if (basename === "readme.md") return "readme";
  if (basename.includes("architecture")) return "architecture";
  return "doc";
}

export function inferFeatureId(relPath: string, relSpecsRoot: string): string | null {
  const normalized = relPath.replace(/\\/g, "/");
  const prefix = relSpecsRoot.replace(/\\/g, "/").replace(/\/$/, "") + "/";
  if (!normalized.startsWith(prefix)) return null;
  const rest = normalized.slice(prefix.length);
  const parts = rest.split("/");
  return parts.length > 0 && parts[0] ? parts[0] : null;
}

export async function discoverDocFiles(projectRoot: string, config: MemoryHubConfig): Promise<string[]> {
  const patterns =
    config.indexing.include.docs.length > 0
      ? config.indexing.include.docs
      : ["docs/**/*.md", "specs/**/*.md", "README.md"];

  const files = await fg(patterns, {
    cwd: projectRoot,
    absolute: false,
    dot: true,
    onlyFiles: true,
    ignore: config.indexing.exclude,
  });

  return files.filter((filePath) => {
    const basename = path.basename(filePath);
    return !PHASE1_BASENAMES.has(basename) && !GENERATED_BASENAMES.has(basename);
  });
}

function chunkDocToEntry(
  relPath: string,
  chunk: ParsedChunk,
  now: string,
  relSpecsRoot: string,
): MemoryEntryRecord {
  const artifactType = inferArtifactType(relPath);
  const featureId = inferFeatureId(relPath, relSpecsRoot);
  const id = shortId([relPath, chunk.section_heading, chunk.line_start, chunk.line_end, chunk.hash].join("|"));

  const extraTags = [`artifact:${artifactType}`];
  if (featureId) extraTags.push(`feature:${featureId}`);

  const allTags = [...new Set([...chunk.tags, ...extraTags])].sort().join(",");

  return {
    id,
    source_path: relPath,
    source_type: "doc" as MemorySourceType,
    section_heading: chunk.section_heading,
    content_summary: chunk.summary,
    snippet: chunk.snippet,
    tags: allTags,
    hash: chunk.hash,
    line_start: chunk.line_start,
    line_end: chunk.line_end,
    updated_at: now,
    created_at: now,
    status: "active",
  };
}

export async function indexDocFiles(
  projectRoot: string,
  db: MemoryDatabase,
  config: MemoryHubConfig = loadConfig(projectRoot),
  options: IndexDocOptions = {},
): Promise<IndexDocResult> {
  const { specsRoot } = resolveProjectPaths(projectRoot, config);
  const relSpecsRoot = path.relative(projectRoot, specsRoot);

  const files = await discoverDocFiles(projectRoot, config);
  const stateMap = loadIndexingStateMap(db, "doc");
  const now = new Date().toISOString();

  const result: IndexDocResult = {
    scannedFiles: files.length,
    indexedFiles: 0,
    skippedFiles: 0,
    deletedFiles: 0,
    indexedEntries: 0,
  };

  const seenPaths = new Set<string>();

  for (const relPath of files) {
    seenPaths.add(relPath);
    let raw: string;
    try {
      raw = await readTextFile(path.resolve(projectRoot, relPath));
    } catch {
      result.skippedFiles += 1;
      continue;
    }

    const hash = sha256(raw);
    const existing = stateMap.get(relPath);
    if (options.refreshOnly && existing?.hash === hash) {
      result.skippedFiles += 1;
      continue;
    }

    const chunks = parseMarkdownFile(relPath, raw).map((chunk) =>
      chunkDocToEntry(relPath, chunk, now, relSpecsRoot),
    );
    upsertIndexedFile(db, relPath, "doc", hash, now, chunks);
    result.indexedFiles += 1;
    result.indexedEntries += chunks.length;
  }

  if (options.removeDeleted !== false) {
    // Only consider removing paths that were previously indexed as doc entries
    // (i.e., not Phase 1 files) and are no longer discovered.
    const missingDocPaths = [...stateMap.keys()].filter(
      (sp) => !PHASE1_BASENAMES.has(path.basename(sp)) && !seenPaths.has(sp),
    );
    for (const sourcePath of missingDocPaths) {
      deleteSourceEntries(db, sourcePath, "doc");
      result.deletedFiles += 1;
    }
  }

  return result;
}
