import path from "path";
import { loadConfig, resolveProjectPaths } from "../config";
import { MemoryDatabase } from "../db";
import { searchDocEntries } from "../retrieval/docs";
import { MemoryHubConfig, SearchResult } from "../types";
import { writeTextFile } from "../utils/fs";
import { truncateWords, wordCount } from "../utils/text";

export interface DocSynthesisResult {
  feature: string;
  outputPath: string;
  content: string;
  words: number;
  sourceFiles: string[];
}

function featureNameFromPath(featurePath: string): string {
  return path.basename(featurePath.replace(/[\\/]+$/, ""));
}

function formatDocSection(title: string, entries: SearchResult[], maxSnippetWords = 60): string {
  if (entries.length === 0) return "";
  const lines = entries.map((e, i) => {
    const text = e.content_summary || e.snippet || e.section_heading || e.source_path;
    return `- [${String(i + 1)}] ${truncateWords(text, maxSnippetWords)} (${e.source_path})`;
  });
  return `## ${title}\n${lines.join("\n")}`;
}

/**
 * Generate a compact `doc-synthesis.md` for a feature by retrieving the top
 * relevant chunks from the Phase 2 doc cache — spec, plan, tasks, constitution,
 * architecture notes, and security constraints — and assembling them into a
 * single low-token summary the AI can read instead of opening every file.
 */
export async function generateDocSynthesis(
  db: MemoryDatabase,
  projectRoot: string,
  featurePath: string,
  config: MemoryHubConfig = loadConfig(projectRoot),
): Promise<DocSynthesisResult> {
  const featureName = featureNameFromPath(featurePath);
  const { specsRoot } = resolveProjectPaths(projectRoot, config);
  const outputPath = path.resolve(projectRoot, featurePath, "doc-synthesis.md");

  // Convert feature folder name to a search query (e.g. "001-auth" → "001 auth").
  const searchQuery = featureName.replace(/[-_]/g, " ");

  const specs = searchDocEntries(db, searchQuery, config, {
    featureId: featureName,
    artifactType: "spec",
  });
  const plans = searchDocEntries(db, searchQuery, config, {
    featureId: featureName,
    artifactType: "plan",
  });
  const tasks = searchDocEntries(db, searchQuery, config, {
    featureId: featureName,
    artifactType: "tasks",
  });
  // Constitution and architecture/security are project-wide (no featureId filter).
  const constitutions = searchDocEntries(db, searchQuery, config, {
    artifactType: "constitution",
  });
  const architectureDocs = searchDocEntries(db, searchQuery, config, {
    artifactType: "architecture",
  });
  const securityDocs = searchDocEntries(db, searchQuery, config, {
    artifactType: "security",
  });

  const sections = [
    `# Doc Synthesis — ${featureName}`,
    `_Generated by Spec Kit Memory Hub. Read this file instead of opening individual docs._`,
    `_Feature: \`${featurePath}\`_`,
    "",
    formatDocSection("Spec", specs),
    formatDocSection("Plan", plans),
    formatDocSection("Tasks", tasks),
    formatDocSection("Constitution & Governance", constitutions),
    formatDocSection("Architecture Notes", architectureDocs),
    formatDocSection("Security Constraints", securityDocs),
  ].filter(Boolean);

  const content = sections.join("\n\n").trim() + "\n";
  const words = wordCount(content);

  const sourceFiles = [
    ...new Set(
      [...specs, ...plans, ...tasks, ...constitutions, ...architectureDocs, ...securityDocs].map(
        (e) => e.source_path,
      ),
    ),
  ];

  return { feature: featureName, outputPath, content, words, sourceFiles };
}

export async function writeDocSynthesis(
  db: MemoryDatabase,
  projectRoot: string,
  featurePath: string,
  config: MemoryHubConfig = loadConfig(projectRoot),
): Promise<DocSynthesisResult> {
  const synthesis = await generateDocSynthesis(db, projectRoot, featurePath, config);
  await writeTextFile(synthesis.outputPath, synthesis.content);
  return synthesis;
}
